### ISSUE TITLE
Extraneous endif in Makefile

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#38]
Hi,
great to see you're still working on this wonderful project :)
Just got a small fix for the Makefile. I don't really know Makefiles, but the indentation makes me think that an "if" or similar was removed at the top level at line 27. In any case, commenting out the "endif" in line 61 fixes the build for me.

Cheers, Steffen

**Comment by jamespetts** [comment]
Splendid, thank you for spotting that. Now fixed.

**Comment by steffen123** [comment]
7 minutes fix time, nice one!
