### ISSUE TITLE
Segfault in weg_t::get_signal(unsigned char) const ()

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#39]
Hi,
I'm having a reproducible segfault with my savegame. I'm not sure how to attach files here, what's your preferred way of getting them?

SE-version: c3f779820d2d23656f8811b57db04ca992ceda40
Pak: britain-ex from friday, with an added narrow gauge one way signal, I just copied the rail signal and changed name and carrier type (but there is no narrow gauge in this game)

Pre-Story: I saved and quit the game because it got "stuck" in the Routing. Roughly in the middle of the map there is a bit of single track at e.g. 1607,659. The train in the east (#20) and in the west (#27) both want to go onto this section but neither did. I had issues of this kind before and so far I was unable to reproduce them after loading. That issue doesn't appear after loading, however, it segfaults. I don't know if the segfault and the above issue are related, but from the backtrace, it might be? I also have a savegame from about half an hour before this, I think the last things I did before the crashing game was send 3 trains to depot, and add a new one from the depot at Oldden (that has to go through the single track section mentioned). 

To reproduce: Just load the game and let it run for a few seconds. It should crash shortly, e.g. I just re-tried and it crashed at 1915, September, 1:38:11.

Program received signal SIGSEGV, Segmentation fault.
0x00005555556179e4 in weg_t::get_signal(unsigned char) const ()
(gdb) bt
#0  0x00005555556179e4 in weg_t::get_signal(unsigned char) const ()
#1  0x0000555555986715 in rail_vehicle_t::can_enter_tile(grund_t const*, int&, unsigned char) ()
#2  0x000055555596ea80 in vehicle_t::hop_check() ()
#3  0x0000555555971c3f in vehicle_base_t::do_drive(unsigned int) ()
#4  0x0000555555883464 in convoi_t::sync_step(long) ()
#5  0x000055555592fb1d in karte_t::sync_step(long, bool, bool) ()
#6  0x00005555558cc007 in interrupt_check() ()
#7  0x000055555594666e in karte_t::interactive(unsigned int) ()
#8  0x00005555558d6519 in simu_main(int, char**) ()
#9  0x00005555558f0cdd in sysmain(int, char**) ()
#10 0x00007ffff6731154 in __libc_start_main () from /lib64/libc.so.6
#11 0x00005555555ac56b in _start ()

Running on 64 bit Linux and I got the backtrace from gdb. I can apply patches to diagnose or try to fix this easily.

**Comment by steffen123** [comment]
Oh and in the process of adding those trains I also doubled up a few more sections (like what I have all over the place, so trains can pass each other).

**Comment by jamespetts** [comment]
Thank you for your report: can you e-mail the saved game to me at 
jamespetts@yahoo.com?

**Comment by steffen123** [comment]
Sent. It might go into your spam folder.

**Comment by jamespetts** [comment]
I think that I have fixed this now. Can you re-test?

**Comment by steffen123** [comment]
Tried commit be5fba1cabad15d0cda070136fd13cf972d7ae64, works now, thanks!

**Comment by jamespetts** [comment]
Splendid, thank you for testing.
