### ISSUE TITLE
Goods aren't showing up in storage at one steel mill

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#40]
Hello,
whilst you were on the last one I started a new game and encountered another issue.

I think I created this game on commit c3f779820d2d23656f8811b57db04ca992ceda40, and I just verified it still exists on commit be5fba1cabad15d0cda070136fd13cf972d7ae64. I should note that I set maximum_intransit_percentage=500. I'll take the liberty and mail you the savegame again, hope that's ok.

The issue affects the steel mill at 346,405. Goods are transported to it by the trains (one each for coal+iron).

On the old commit: They are registered as arrived for the trains and for the station at the steel mill, but not at the actual steel mill (I'm going by the data from the respective charts here). But they also don't stay at the station. It did however appear that the steel mill still maxed out it's maximum_intransit_percentage - eventually the train would sit at the colliery at low load. So somehow the freight appears to be "stuck" between the station at the steel mill, and the steel mill. I'm 99% certain I tried saving, quitting the whole game and restarting&loading it.

On the new commit: Now the freight doesn't stay in transit anymore, so the trains run indefinitely. They also no longer show up in the steel mill's station's chart, but they do still show up as delivered in the train's chart.

I built a train to a different steel mill at 544,927 and that works as normal.

Cheers, Steffen

**Comment by jamespetts** [comment]
I think that I have just fixed this - would you mind testing to confirm? 
Thank you for your report.

James.

**Comment by steffen123** [comment]
Tried commit 37758897e139561079794c230821df35ab310ecf, now it works, thanks :)

**Comment by jamespetts** [comment]
Splendid, thank you for letting me know.
