### ISSUE TITLE
Electricity network partially shuts down on month end (reproducible)

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#41]
Hi, sorry to be bombarding you like this ;)
I am happy to bisect by the way, what's the earliest tag/commit that will load my saves correctly?

Now, onto the bug.

Backstory:
Same game as in #40, I now started building an electricity network of Paris&Amsterdam. When I connected amsterdam I first tried with a substation at 338,404, but that didn't work. So I figured maybe that's not connected to the city and built one at 360,405 instead. That also didn't work. So I saved and either reloaded or quit&reloaded (I think the latter, but not certain). Then it worked, power usage went up to ~70 MW, or would've if I had had enough generation connected (btw, the transformers show KW instead).

Steps to reproduce:
Then February 1925 started and usage dropped to 8 MW. So saved (I'll send you this savegame) quit and reloaded, and usage was back to normal. Fast forward to March and usage drops back to 8 MW. I quit and reloaded the February savegame to confirm, and it happens reliably.

Possibly related: I occasionally notice trains stopped on their track after track changes and/or schedule changes. Reloading always fixes those so I don't have anything really reportable, but I thought this could potentially be related.

Cheers, Steffen

**Comment by steffen123** [comment]
Maybe this is even related to what you noted as the old desync bug at http://forum.simutrans.com/index.php?topic=14690.0

**Comment by jamespetts** [comment]
That is certainly possible: when I fix this, we will have to re-test the 
desync bug.

**Comment by jamespetts** [comment]
I think that I have fixed the electrical problem: there was a bug in the 
code that checked whether factories were connected to towns, which 
resulted in them sometimes not being regarded as connected to towns even 
though they were. That is now fixed: would you be able to confirm that 
this is working for you? It would be interesting to see whether this 
fixes the desync issues.

**Comment by steffen123** [comment]
Thank you, tried commit 149fbc3c2af79af05424aa964188a13d5165ca81 and the reported bug (power demand disappearing on month-end) is gone. Energy demand also goes up from 72 MW to 80 MW, which appears to be due to Paris Colliery. This also fits well with what you described. Note that the increase in power use only appears at month-end, but I'd assume that is only an artefact of the fixed bug and would only appear in games from before the bugfix.

I can't speak for the desync issue though but I'm happy to arrange for a test. My computer takes approx 4 Minutes to rebuild from devel-new, and I can apply patches manually.


However there appears to be another two bugs, possibly related to either or both of the discussed.

New backstory: I loaded my last savegame with the previous version (d1927-09), destroyed the substations at Leipzig (this one had 2) and Nantes and the last 5 squares each of the power line. Then I let the game run to month end, saved (d1927-10), quit the game, reloaded.

1. When I load the -10 savegame power demand is again down to 72 MW. At month end (ie Nov 1927) it is back up to 80 MW. Letting it run on into Dec doesn't change anything and demand stays at 80 MW.

2. This one I had noticed between opening this issue and your bug. When I connected Nantes and Leipzig they didn't draw power (checked the power line info dialogue, and the cities' power usage). I destroyed those connections as described above and rebuilt them now in Dec (without pausing, just in case), and they again don't connect.
For Nantes I built the line first, then placed the substation on the last square of the line. For Leipzig I did it the other way round. When I connected the power line to Leipzig's new substation the numbers on the power line info screen momentarily dropped to 0 except demand dropped to 24 (Leipzig's demand) and then all went back up to the previous numbers. But even without Nantes demand should now be ~104 MW. Letting it run to month end doesn't change anything, demand stays at 80 MW. I saved again and am sending you this one. This savegame also exhibits the 72 MW issue so I'm only sending this one.

**Comment by steffen123** [comment]
PS: almost forgot, the 72 MW issue also appears when simply saving and immediately reloading, it is not necessary to quit.

**Comment by jamespetts** [comment]
Thank you very much for the report. Can you check with the latest commit 
to see whether any of these bugs are fixed? I am afraid that I did not 
get your saved game, but I have found and fixed a specific set of bugs 
that might have caused this (and might also have been responsible for 
the desync).

**Comment by steffen123** [comment]
Hi,
I updated to 87f21c16726732ac8960c4bf5ce9e64e66015bd8. The 72 MW issue is gone now, too, thanks. That leaves just the final one I had in this general area, Nantes&Leipzig aren't connecting. I've sent you the latest one (still created with the last game version I had). Make sure to check your spam folder, my mail server still needs something so my mails don't get treated as spam ;)

**Comment by jamespetts** [comment]
I do not think that this is actually a bug at all: the power demand is 
measured in Kilowatts, not Megawatts: people used much, much less 
electricity in the olden days, so towns without industry will have a 
very limited demand.

However, I did find a bug related to this issue in the towns' power 
supply graphs, which would round down to zero when the power demand was 
low. I have fixed this by changing the scale of the graph based on the 
demand.

Can you confirm that, understood as kW properly as displayed, there is 
no bug apparent?

**Comment by steffen123** [comment]
Ah, I had assumed the kW is a bug. In that case you may well be right, if industry is counted as town demand in the town's graphing? I'm updating to db045c0492c3a205c99ebbb148d3496a8f60ec1b now.

**Comment by jamespetts** [comment]
Industries that are in a town draw from the town's electricity supply, 
and are indeed included in the town's graphs.

**Comment by steffen123** [comment]
Ok, in that case the issue was indeed in my understanding, not the game ;) Thank you
