### ISSUE TITLE
Trams skipping stops/showing wrong info about destination

### ISSUE THREAD

**Issue by steffen123** [jamespetts/simutrans-experimental#42]
Hello, got another weird one ;)
The game was last played with and possibly also created with db045c0492c3a205c99ebbb148d3496a8f60ec1b. I had installed 32d9f17ef0594a35dcf0c296b66ce6cd58c8370a, and I *think* I have been using that version for the whole backstory. However, I definitely used it for the error that I can reproduce.

Backstory:
- I had some trouble with my Leipzig A tram line, accidentally sending new trams from the depot at 5603,1164 to stop A17 as start stop, instead of A1. This caused some blockage but i had noticed it quickly.
- Then I realised that the A line trams are skipping stop A2. They could serve it - If I opened a tram departing from A1 and set its target to A2 it stopped there as expected. Judging by the passenger-waiting chart this might have been going on for a while, though the large number of waits might have also been caused by insufficient capacity on my network. Also, I realised there seems to be a new feature, that vehicles skip stops if they are completely full, until the next stop where they can drop off passengers? If that is indeed a new feature then it might also explain the buildup of passengers at A2.
- I saved the game, quit the game completely and loaded again, hoping the error would stay so it can be fixed - unfortunately the error was gone. But instead I had another issue, and maybe it's related.

To reproduce:
- Load the savegame (I'll mail it to you as usual, hope thats ok).
- Watch the trams departing from stop A17. They target A2, but stop at A1 - and they don't merely stop due to waiting for a free track or something, they exchange passengers.

There was nothing relevant in the shell output nor the simu.log file (I run the game with -log 1 as per the bug reporting instructions)

Cheers, Steffen

**Comment by steffen123** [comment]
Correction, just reloaded the game (the same one that I sent you) and this happened (basically immediately after I loaded):
- I added an 18th tram to Leipzig A line.
- I was watching vehicle (13) on that line. It targeted A2, but stopped and boarded/deboarded at A1. It then targeted A3 and had 27 direct and 9 changing passengers for stop A2 - but now it skipped stop A2.

If I can help you by bisecting or anything pls let me know

**Comment by steffen123** [comment]
And another PS, sorry:
I continued the game and this happened (everything from the last post and this one was inside 30 or 60s):
- I watched vehicle (76) depart stop A17. It targeted A1, which is incorrect - it should target the waypoint which is the last entry in the line's schedule. When it passed through the waypoint it suddenly targetted A2.

So I suspect this might have something to do with the waypoints code.

**Comment by jamespetts** [comment]
On 14/08/15 20:36, steffen123 wrote:
>
> And another PS, sorry:
> I continued the game and this happened (everything from the last post 
> and this one was inside 30 or 60s):
>
>   * I watched vehicle (76) depart stop A17. It targeted A1, which is
>     incorrect - it should target the waypoint which is the last entry
>     in the line's schedule. When it passed through the waypoint it
>     suddenly targetted A2.
>
> So I suspect this might have something to do with the waypoints code.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jamespetts/simutrans-experimental/issues/42#issuecomment-131216185>.
>
Thank you for your various reports. I am currently away for a few days, 
so unable to work on the code until I return. In the meantime, I should 
explain the waypoints system: if a convoy is routed through a waypoint 
at which it does not have to reverse, it routes all the way through to 
the destination rather than getting to the waypoint then routing from 
the waypoint to the next destination. This means that it reserves a path 
ahead of the next waypoint and that waypoints are not treated as if they 
were signals.

Does this explain any of what you are seeing?

James.

**Comment by steffen123** [comment]
No rush.
It does explain one optical "issue" - I'm sure the trams departing A17 (towards the waypoint, and on to A1) would've shown waypoint as the destination in past versions, now they show A1. But that's great - one reason I didn't like using waypoints is that it then showed "waypoint" as dest and the only way to find out the next stop was to open the schedule, stopping the vehicle.

But beyond that, without looking at the code (sorry, at some point in my life I developed a C/C++ phobia ;) ), I think it makes me better at guessing what is happening, but if I'm not mistaken I think there's an actual issue here.

Removing the waypoint "fixed" my issue, but when I had it in trams would skip stop A2 (not sure if always, but the aforementioned vehicles I manually observed did). I would guess the issue might be that the routing via waypoints doesn't correctly handle updating at which step in a schedule the vehicle is.

**Comment by jamespetts** [comment]
If the trams are actually skipping stops, that seems incorrect. I will 
have to look into that when I get back home. Thank you for your report;

James.

**Comment by jamespetts** [comment]
I think that I have now fixed this - would you care to re-test to be 
sure, and check that there are no side effects? Thank you for the report.

**Comment by steffen123** [comment]
Hello,
I'm very sorry for the delay, I was busy with work and quite honestly I simply forgot. However, I think I did run an updated version, and whilst (as I recall) I didn't re-test for my bug I certainly didn't encounter any other issues. I have now updated to the current simexp and pakbritexp but I cannot load my old savegame (will open a new issue).

So I made a new game and just built a quick line. It goes stop 1 -> waypoint (between 1 and 2) -> stop 2 -> stop 3 (and the rest of the stops)
When I make a new tram it goes to stop 1, then gives "Waypoint [<<]" as destination yet travels all the way to stop2. Then it gets stuck there with its speed going back and forth between 1 and 2 kph. It doesnt visibly move at all. I emailed you the savegame as usual.

As always, I can try bisecting this, just tell me where to start :)

Cheers

**Comment by jamespetts** [comment]
Steffen,

thank you for your feedback, and apologies for the delay in replying. I 
have recently fixed a bug that might be the cause of the issue that you 
describe. Could you re-test to see whether it fixes your issue before I 
look into this fully? I should be very grateful.

As to your older saved games, have you enabled the relevant 
SPECIAL_RESCUE builds?

James.

**Comment by steffen123** [comment]
Updated to ac848e560d92d5053ccb068bf70c4bdaff1714f1 and i can no longer reproduce, tyvm.
Note: I didn't try on the old commit whether the bug still occurs after restarting the game, but building a second similar partial line didn't produce it either.
